version: "3"

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    networks:
      - meetwork

  redis:
    image: redis:5
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass password --port 6379
    ports:
      - "6379:6379"
    networks:
      - meetwork

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: meetwork
      MINIO_ROOT_PASSWORD: meetworkpass
    restart: always
    shm_size: '1gb'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

volumes:
  pgdata:
    external: true

networks:
  meetwork:
    labels:
      - meetwork