version: "3"

services:
  database:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    networks:
      - meetwork

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass password --port 6379
    ports:
      - "6379:6379"
    networks:
      - meetwork

  minio:
    image: minio/minio
    container_name: minio
    command: server --address ":9000" --console-address ":9001" /bucket
    env_file:
      - ./env/.env
    restart: always
    shm_size: '1gb'
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

networks:
  meetwork:
    labels:
      - meetwork
