version: "3"

services:
  database:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    networks:
      - meetwork

  redis:
    image: redis:5
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass password --port 6379
    ports:
      - "6379:6379"
    networks:
      - meetwork

networks:
  meetwork:
    labels:
      - meetwork