version: "3"

services:
  database:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=meetwork
      - POSTGRES_USER=meetwork
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - meetwork

  redis:
    image: redis:6
    volumes:
      - ./data/redis:/data
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - meetwork

networks:
  meetwork:
    labels:
      - meetwork
