server:
  port: 80

spring:
  application:
    name: meetwork

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
