server:
  port: 8080

spring:
  application:
    name: meetwork

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: meetwork
    password: password
    url: jdbc:mysql://localhost:3306/meetwork

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password: password

jwt:
  secret: ZGFua29vay11bml2LmFza3VwLXNlcnZlci5qd3Quc2VjcmV0c3xkYW5rb29rLXVuaXYuYXNrdXAtc2VydmVyLmp3dC5zZWNyZXRzCg==
