server:
  port: 80

spring:
  application:
    name: meetwork

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetwork
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
