server:
  port: 80

spring:
  application:
    name: meetwork

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true