server:
  port: 8080
  tomcat:
    max-http-form-post-size: 1024MB
    max-swallow-size: 1024MB

spring:
  application:
    name: meetwork

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetwork
    username: meetwork
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password: password

jwt:
  secret: ZGFua29vay11bml2LmFza3VwLXNlcnZlci5qd3Quc2VjcmV0c3xkYW5rb29rLXVuaXYuYXNrdXAtc2VydmVyLmp3dC5zZWNyZXRzCg==
