name: deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_NAME: meetwork
  DOCKER_IMAGE: ghcr.io/dankook-univ/meetwork-server

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 1. set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 2. grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 3. build with gradle
        run: ./gradlew clean build -x test

      - name: 4. set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.7.0

      - name: 5. set up docker layer caches
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 6. login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 7. docker build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    name: deploy
    needs: build
    runs-on: [ self-hosted, ncp ]
    steps:
      - uses: actions/checkout@v3

      - name: 1. login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 2. docker run
        run: |
          ~/application/cmd/start_docker.sh ${{ env.DOCKER_NAME }} ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 80:80 \
          --net meetwork \
          --name ${{ env.DOCKER_NAME }} \
          --restart always ${{ env.DOCKER_IMAGE }}:latest \
          --DB_USERNAME=${{ secrets.DB_USERNAME }} \
          --DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --DB_URL=${{ secrets.DB_URL }} \
          --REDIS_HOST=${{ secrets.REDIS_HOST }} \
          --REDIS_PORT=${{ secrets.REDIS_PORT }} \
          --REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
          --MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }} \
          --MINIO_BUCKET=${{ secrets.MINIO_BUCKET }} \
          --MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }} \
          --MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }} \
          --JWT_SECRET=${{ secrets.JWT_SECRET }}
